@startuml
hide empty members
abstract class Alpha<<PolicyCmptType>> { 
  +status: String
  ~derivedValue: Integer
  #computedAmount: Decimal
  -TYPE_CODE: String
}
Alpha *-- Beta
class Beta<<(V,lightSteelBlue)PolicyCmptType>> { 
  +statusKind: data.Status
  +unknownRef: data.UnknownEnum
}
Alpha <|-- Beta
@enduml