@startuml
hide empty members
abstract class Alpha<<PolicyCmptType>> { 
  -TYPE_CODE: String
  #computedAmount: Decimal
  ~derivedValue: Integer
  +status: String
}
Alpha *-- Beta
Delta <-- Alpha
class Beta<<(V,lightSteelBlue)PolicyCmptType>> { 
  +statusKind: data.Status
  +unknownRef: data.UnknownEnum
}
Alpha <|-- Beta
class Delta<<(V,lightSteelBlue)PolicyCmptType>> { 
  +coverageId: String
}
@enduml